global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'faas-netesd'
    static_configs:
      - targets: ['faas-netesd:8081']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'queue-worker'
    static_configs:
      - targets: ['queue-worker:8080']
    metrics_path: /metrics
    scrape_interval: 5s 