apiVersion: v1
kind: Namespace
metadata:
  name: mspr2-cofrap
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mspr2-cofrap
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=  # "password" en base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mspr2-cofrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: enock17/mspr2-postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: "mspr2_cofrap"
        - name: POSTGRES_USER
          value: "postgres"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mspr2-cofrap
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 